@startuml

title __TASK2's Class Diagram__\n


    namespace om.example.task2 {
      class com.example.task2.HelloApplication {
      }
    }

  


    namespace om.example.task2 {
      class com.example.task2.HelloController {
      }
    }

  


    namespace om.example.task2 {
      namespace model {
        class com.example.task2.model.Factory {
        }
      }
    }

  


    namespace om.example.task2 {
      namespace model {
        interface com.example.task2.model.IFactory {
        }
      }
    }

  


    namespace om.example.task2 {
      namespace model {
        class com.example.task2.model.myAngle {
        }
      }
    }

  


    namespace om.example.task2 {
      namespace model {
        class com.example.task2.model.myCircle {
        }
      }
    }

  


    namespace om.example.task2 {
      namespace model {
        class com.example.task2.model.myRect {
        }
      }
    }

  


    namespace om.example.task2 {
      namespace model {
        abstract class com.example.task2.model.myShape {
        }
      }
    }


    namespace om.example.task2 {
      namespace model {
        class com.example.task2.model.myTriangle {
        }
      }
    }

  

  com.example.task2.HelloApplication -up-|> javafx.application.Application
  com.example.task2.HelloController .up.|> javafx.fxml.Initializable
  com.example.task2.HelloController o-- com.example.task2.model.myShape : circ
  com.example.task2.HelloController o-- com.example.task2.model.myShape : rect
  com.example.task2.HelloController o-- com.example.task2.model.myShape : trig
  com.example.task2.model.Factory .up.|> com.example.task2.model.IFactory
  com.example.task2.model.myAngle -up-|> com.example.task2.model.myShape
  com.example.task2.model.myCircle -up-|> com.example.task2.model.myShape
  com.example.task2.model.myRect -up-|> com.example.task2.model.myShape
  com.example.task2.model.myTriangle -up-|> com.example.task2.model.myShape


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
